# Generated by Django 5.1 on 2024-08-22 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(help_text='Укажите свой Email', max_length=255, unique=True, verbose_name='Контактный email')),
                ('full_name', models.CharField(help_text='Укажите свои Ф.И.О.', max_length=255, verbose_name='Ф.И.О.')),
                ('comment', models.TextField(blank=True, help_text='Оставьте комментарий', null=True, verbose_name='Комментарий')),
            ],
        ),
    ]
