# Generated by Django 5.1 on 2024-08-26 10:16

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0003_client_owner_mailing_owner_message_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailing',
            name='first_send_datetime',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата и время первой отправки рассылки'),
        ),
    ]
