# Generated by Django 5.1 on 2024-09-03 10:35

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0006_alter_mailing_message_alter_mailingattempt_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mailingattempt',
            name='attempt_datetime',
        ),
        migrations.AddField(
            model_name='mailingattempt',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата и время окончания рассылки'),
        ),
        migrations.AddField(
            model_name='mailingattempt',
            name='first_send_datetime',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата и время начала рассылки'),
        ),
        migrations.AlterField(
            model_name='mailing',
            name='status',
            field=models.CharField(choices=[('Создана', 'Создана'), ('Запущена', 'Запущена'), ('Завершена', 'Завершена')], default='Создана', max_length=10, verbose_name='Статус рассылки'),
        ),
    ]
