# Generated by Django 5.1 on 2024-09-03 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0007_remove_mailingattempt_attempt_datetime_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mailingattempt',
            old_name='response',
            new_name='server_response',
        ),
    ]
