# Generated by Django 4.2.2 on 2024-09-04 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0008_rename_response_mailingattempt_server_response'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mailing',
            options={'permissions': [('can_view_mailing', 'Can view mailing'), ('can_view_users', 'Can view users'), ('can_block_users', 'Can block users'), ('can_block_mailing', 'Can block mailing')], 'verbose_name': 'Рассылка', 'verbose_name_plural': 'Рассылки'},
        ),
    ]
