# Generated by Django 4.2.2 on 2024-09-04 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0010_mailing_is_active'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mailing',
            options={'permissions': [('can_view_mailing', 'Can view mailing'), ('can_mailing_is_active', 'Can mailing is active')], 'verbose_name': 'Рассылка', 'verbose_name_plural': 'Рассылки'},
        ),
    ]
