# Generated by Django 4.2.2 on 2024-09-06 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0012_alter_mailingattempt_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='mailing',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата и время окончания рассылки'),
        ),
        migrations.AlterField(
            model_name='mailing',
            name='periodicity',
            field=models.CharField(choices=[('Ежедневно', 'Ежедневно'), ('Еженедельно', 'Еженедельно'), ('Ежемесячно', 'Ежемесячно')], default='Ежедневно', help_text='Выберите периодичность рассылки', max_length=20, verbose_name='Периодичность рассылки'),
        ),
    ]
