# Generated by Django 4.2.2 on 2024-09-06 09:32

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0014_alter_mailingattempt_end_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailing',
            name='end_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата и время окончания рассылки'),
            preserve_default=False,
        ),
    ]
