# Generated by Django 4.2.2 on 2024-09-06 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0015_alter_mailing_end_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailing',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата и время окончания рассылки'),
        ),
        migrations.AlterField(
            model_name='mailingattempt',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата и время окончания рассылки'),
        ),
    ]
