# Generated by Django 4.2.2 on 2024-09-05 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Укажите название блога', max_length=100, verbose_name='Заголовок блога')),
                ('body', models.TextField(help_text='Введите содержание статьи', verbose_name='Содержание статьи')),
                ('image_blog', models.ImageField(blank=True, help_text='Загрузите изображение', null=True, upload_to='blog/', verbose_name='Изображение')),
                ('views_count', models.IntegerField(default=0, verbose_name='Количество просмотров')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'Блог',
                'verbose_name_plural': 'Блоги',
            },
        ),
    ]
